
const usernameBlacklist = [
    'nightbot',
    'streamelements',
    'soundalerts',
    'streamlabs',
    'botterkat',
    'kofistreambot',
];

const emoteWhitelist = [
    '7tv'
];

const responses = {
    message: [
        "Welcome, ${username}! Enjoy the cosmic vibes!",
        "Greetings, ${username}! Thanks for joining us!",
        "Hello there, ${username}! It's great to see you in the chat!",
        "Hey, ${username}! The cosmic adventure begins now. Buckle up!",
        "Greetings, ${username}! Your presence makes the stream shine brighter!",
        "Welcome, ${username}! Your arrival brings a new spark to the cosmic journey!",
    ],
    follower: [
        "Thanks for following, ${username}! Enjoy the cosmic journey!",
        "Welcome, ${username}! Let's explore the universe together!",
        "Appreciate the follow, ${username}! Your support means the world!",
        "Glad to have you as a follower, ${username}! May your galactic journey be amazing!",
        "Welcome to the Orion constellation, ${username}! Get ready for an out-of-this-world experience!",
        "Hey there, ${username}! Join our interplanetary gaming adventure!",
        "Welcome to the Orion constellation, ${username}! Let's conquer galaxies together!",
        "Thanks for joining our celestial realm, ${username}! Get ready for cosmic gameplay!",
        "Step into the cosmic portal, ${username}! Let's explore virtual galaxies!",
        "Thank you for joining our cosmic caravan, ${username}! Let's traverse the universe!",
        "Calling all star beans! ${username} has followed. Get ready for an epic gaming odyssey!",
        "Prepare for a cosmic odyssey, ${username}! Explore the universe in games!",
    ],
    sub: [
        "Thanks ${username} for ${amount} stellar months of support!",
        "Celestial cheers, ${username}! Join us for ${amount} months of cosmic exploration!",
        "Shoutout to ${username}! ${amount} months in our Orion Constellation! Your subscription powers our cosmic journey.",
        "Appreciate your subscription, ${username}! ${amount} months of cosmic commitment!",
        "Welcome, ${username}! Explore the cosmos with us for ${amount} months!",
        "Cosmic gratitude, ${username}! ${amount} stellar months of support!",
        "Celestial greetings, ${username}! A ${amount}-month subscription shining like a supernova.",
        "Stellar salute, ${username}! ${amount} months of loyal star bean support!",
        "Celestial blessings, ${username}! Keep the cosmic energy flowing with your ${amount}-month subscription.",
        "Thanks ${username} for the ${amount}-month cosmic subscription! Your commitment fuels us.",
        "Welcome back, ${username}! ${amount}-month subscription adding celestial sparkles!",
        "Thanks ${username} for ${amount} stellar months! Your support ignites us.",
        "Celestial applause, ${username}! ${amount}-month subscription guiding us.",
        "Thanks ${username} for the ${amount}-month interstellar subscription! Your support fuels us.",
        "Celestial waves to ${username}! ${amount} months as a star bean in the Orion constellation!",
        "Cosmic shoutout, ${username}! ${amount}-month subscription lighting up our stream.",
        "Thanks ${username} for being a stellar star bean! ${amount} months of support!",
        "Celestial high fives, ${username}! ${amount}-month subscription fueling our cosmic adventures!",
    ],
    sub_gift: [
        "Stellar shoutout to ${sender} for the generous gift! Welcome, ${username}! Enjoy the cosmic journey!",
        "Celestial cheers to ${sender} for the amazing gift! ${username}, join the starbeans for an incredible experience!",
        "Thank you, ${sender}, for the interstellar gift! Welcome to the cosmic family, ${username}!",
        "Celestial gratitude to ${sender} for the generous gift! Welcome aboard, ${username}! Your cosmic journey begins!",
        "Thank you, ${sender}, for the stellar gift! Join our celestial journey, ${username}!",
        "Celestial shoutout to ${sender} for the amazing gift! Welcome to the star beans, ${username}!",
        "Celestial applause to ${sender} for the incredible gift! Welcome to the Orion constellation, ${username}!",
        "Cosmic salute to ${sender} for the generous gift! Enjoy interplanetary gaming, ${username}!",
        "Thank you, ${sender}, for the interstellar gift! Explore the vast reaches of space, ${username}!",
        "Stellar shoutout to ${sender} for the amazing gift! Brighten our cosmic stream, ${username}!",
        "Thank you, ${sender}, for the cosmic gift! Launch us to new gaming heights, ${username}!",
        "Thank you, ${sender} for the stellar gift! Ignite the cosmic fire, ${username}!",
        "Celestial cheers to ${sender} for the amazing gift! Light up our stream, ${username}!",
        "Thank you, ${sender}, for the cosmic gift! Your loyalty fuels us, ${username}!",
        "Stellar shoutout to ${sender} for the incredible gift! Fuel our cosmic adventures, ${username}!",
        "Celestial gratitude to ${sender} for the generous gift! Set the course for intergalactic voyage, ${username}!",
    ],
    sub_bomb: [
        "Cosmic shoutout to ${sender} for an epic star bean supernova of ${amount} subscriptions, igniting our stream with celestial fire!",
        "Incoming star bean supernova! Massive thanks to ${sender} for gifting ${amount} subscriptions, creating a cosmic explosion of excitement!",
        "Hold on tight, star beans! We've encountered a supernova! Thanks to ${sender} for igniting ${amount} subscriptions!",
        "Alert! Witnessed a star bean supernova! Thanks ${sender} for fueling our stream with ${amount} subscriptions!",
        "Thrilled to welcome new star beans to the Orion Constellation! Thanks ${sender} for bringing ${amount} subscriptions!",
        "Stellar shoutout to ${sender} for a star bean supernova of ${amount}, illuminating our stream with cosmic power!",
        "Hold on tight! Prepare for a star bean supernova! Enormous thanks to ${sender} for gifting ${amount} subscriptions!",
        "Honored to have you as part of our supernova-powered community, ${sender}! Welcome ${amount} new star beans to an intergalactic thrill ride!",
    ],
    cheer: [
        "Wow! Thanks ${username} for ${amount} bits! Your support fuels our cosmic journey!",
        "Thank you for ${amount} bits, ${username}! Your generosity keeps the stream going strong.",
        "Thank you, ${username}, for ${amount} bits! Your support is out of this world!",
        "Thanks, ${username}, for ${amount} bits! Your cosmic contribution shines bright.",
        "Grateful for ${amount} bits, ${username}! Your support propels our cosmic adventure!",
    ],
    raid: [
        "Meteor shower alert! ${username} is bringing ${amount} raiders for a cosmic adventure!",
        "Incoming meteor shower! Thanks ${username} for bringing ${amount} raiders!",
        "Cosmic raiders on the radar! Welcome ${username} and your community of ${amount}!",
        "Brace for impact! ${username} brings ${amount} raiders to storm our cosmic sanctuary!",
        "Cosmic raid unleashed! Thanks ${username} for bringing your community of ${amount}!",
        "Welcome raiders! ${username} brings ${amount} raiders like a meteor shower!",
        "Incoming meteor shower! Thanks ${username} for bringing ${amount} raiders!",
        "Attention star beans! ${username} and ${amount} raiders are incoming!",
    ],
};

const imageSources = [
    "https://resources.aonyxlimited.com/frank/0.png",
    "https://resources.aonyxlimited.com/frank/1.png",
    "https://resources.aonyxlimited.com/frank/2.png",
    "https://resources.aonyxlimited.com/frank/3.png",
    "https://resources.aonyxlimited.com/frank/4.png",
    "https://resources.aonyxlimited.com/frank/5.png",
    "https://resources.aonyxlimited.com/frank/6.png",
    "https://resources.aonyxlimited.com/frank/7.png",
    "https://resources.aonyxlimited.com/frank/8.png",
    "https://resources.aonyxlimited.com/frank/9.png",
    "https://resources.aonyxlimited.com/frank/10.png",
]

module.exports = {
    usernameBlacklist: usernameBlacklist,
    responses: responses,
    imageSources: imageSources,
    emoteWhitelist : emoteWhitelist,
}